Repository glue-viz/glue, pull requests merged in 2018-11, with the labels that each got.

#1890 Avoid unecessary warnings
  CHANGES.md
  glue/app/qt/application.py
  glue/viewers/common/qt/base_widget.py
Labels: enhancement

#1893 Make sure qglue works correctly with BaseData subclasses
  glue/core/data_factories/helpers.py
  glue/core/data_factories/tests/test_data_factories.py
  glue/qglue.py
  glue/tests/test_qglue.py
Labels: affects-dev, bug

#1850 Add a custom layer maker registry
  CHANGES.md
  doc/customizing_guide/customization.rst
  glue/app/qt/application.py
  glue/config.py
  glue/core/application_base.py
  glue/core/layer_artist.py
  glue/core/subset.py
  glue/core/tests/test_subset.py
  glue/viewers/common/tests/test_viewer.py
  glue/viewers/common/viewer.py
Labels: Ready for final review, work in progress

#1894 Refactor how we handle aspect ratios to not depend on Matplotlib
  CHANGES.md
  glue/_mpl_backend.py
  glue/app/qt/application.py
  glue/core/data.py
  glue/core/qt/tests/test_layer_artist_model.py
  glue/plugins/exporters/plotly/qt/tests/test_plotly.py
  glue/viewers/histogram/state.py
  glue/viewers/image/qt/tests/test_data_viewer.py
  glue/viewers/image/state.py
  glue/viewers/image/viewer.py
  glue/viewers/matplotlib/qt/tests/test_data_viewer.py
  glue/viewers/matplotlib/state.py
  glue/viewers/matplotlib/tests/__init__.py
  glue/viewers/matplotlib/tests/test_viewer.py
  glue/viewers/matplotlib/viewer.py
  glue/viewers/scatter/qt/tests/test_data_viewer.py
  glue/viewers/scatter/state.py
Labels: Ready for final review, merge-when-ci-passes

#1902 Fix get_mask when key joins are present
  CHANGES.md
  glue/core/data.py
  glue/core/joins.py
  glue/core/subset.py
  glue/core/subset_group.py
  glue/core/tests/test_joins.py
  glue/plugins/dendro_viewer/state.py
Labels: bug

#1903 Fix broken/permanently redirected links
  doc/conf.py
  doc/customizing_guide/available_plugins.rst
  doc/customizing_guide/fitting.rst
  doc/customizing_guide/qt_viewer.rst
  doc/customizing_guide/writing_plugin.rst
  doc/developer_guide/coding_guidelines.rst
  doc/developer_guide/roadmap.rst
  doc/developer_guide/testing.rst
  doc/faq.rst
  doc/getting_started/index.rst
  doc/gui_guide/slice.rst
  doc/installation/dependencies.rst
  doc/installation/glueconda.rst
  doc/python_guide/data_tutorial.rst
  doc/python_guide/glue_from_python.rst
  doc/redirect.py
  doc/videos.rst
  doc/whatsnew/whatsnew.rst
Labels: documention

#1905 Add global widget font preference
  glue/app/qt/application.py
  glue/app/qt/preferences.py
  glue/app/qt/preferences.ui
  glue/app/qt/tests/test_preferences.py
  glue/config.py
  glue/utils/qt/app.py
Labels: enhancement
