Repository glue-viz/glue, pull requests merged in 2018-04, with the labels that each got.

#1636 Improve UI for saving/exporting data
  glue/app/qt/application.py
  glue/app/qt/save_data.py
  glue/app/qt/save_data.ui
Labels: affects-dev, cubeviz, enhancement, gui

#1638 Fix remaining low-resolution icons
  glue/icons/glue_down_arrow.png
  glue/icons/glue_xrange_select.png
  glue/icons/glue_yrange_select.png
Labels: bug, gui, no-changelog-entry-needed

#1635 Refactor spectrum tool
  CHANGES.md
  glue/core/coordinates.py
  glue/core/fitters.py
  glue/core/link_manager.py
  glue/core/qt/fitters.py
  glue/core/qt/tests/test_fitters.py
  glue/core/state_objects.py
  glue/core/tests/test_link_manager.py
  glue/plugins/tools/spectrum_tool/__init__.py
  glue/plugins/tools/spectrum_tool/qt/__init__.py
  glue/plugins/tools/spectrum_tool/qt/profile_viewer.py
  glue/plugins/tools/spectrum_tool/qt/spectrum_fit_panel.ui
  glue/plugins/tools/spectrum_tool/qt/spectrum_tool.py
  glue/plugins/tools/spectrum_tool/qt/tests/test_profile_viewer.py
  glue/plugins/tools/spectrum_tool/qt/tests/test_spectrum_tool.py
  glue/utils/matplotlib.py
  glue/utils/tests/test_matplotlib.py
  glue/viewers/common/qt/data_viewer.py
  glue/viewers/image/qt/data_viewer.py
  glue/viewers/image/qt/profile_viewer_tool.py
  glue/viewers/profile/__init__.py
  glue/viewers/profile/layer_artist.py
  glue/viewers/profile/qt/__init__.py
  glue/viewers/profile/qt/data_viewer.py
  glue/viewers/profile/qt/layer_style_editor.py
  glue/viewers/profile/qt/layer_style_editor.ui
  glue/viewers/profile/qt/mouse_mode.py
  glue/viewers/profile/qt/options_widget.py
  glue/viewers/profile/qt/options_widget.ui
  glue/viewers/profile/qt/profile_tools.py
  glue/viewers/profile/qt/profile_tools.ui
  glue/viewers/profile/qt/tests/__init__.py
  glue/viewers/profile/qt/tests/test_data_viewer.py
  glue/viewers/profile/qt/tests/test_mouse_mode.py
  glue/viewers/profile/qt/tests/test_profile_tools.py
  glue/viewers/profile/state.py
  glue/viewers/profile/tests/__init__.py
  glue/viewers/profile/tests/test_state.py
  setup.py
Labels: enhancement, merge-when-ci-passes, plugin-spectrum-tool, whats-new-needed

#1641 Improve mouse profile performance
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  doc/installation/dependencies.rst
  glue/core/aggregate.py
  glue/core/data.py
  glue/core/link_manager.py
  glue/core/message.py
  glue/core/state.py
  glue/core/state_objects.py
  glue/core/subset.py
  glue/core/tests/test_aggregate.py
  glue/core/tests/test_data_collection.py
  glue/core/tests/test_link_manager.py
  glue/core/tests/test_state_objects.py
  glue/core/tests/test_subset.py
  glue/core/util.py
  glue/dialogs/subset_facet/qt/subset_facet.py
  glue/tests/helpers.py
  glue/utils/array.py
  glue/utils/matplotlib.py
  glue/utils/tests/test_array.py
  glue/viewers/common/qt/data_slice_widget.py
  glue/viewers/histogram/python_export.py
  glue/viewers/image/pixel_selection_mode.py
  glue/viewers/profile/layer_artist.py
  glue/viewers/profile/qt/options_widget.ui
  glue/viewers/profile/qt/profile_tools.py
  glue/viewers/profile/qt/tests/test_data_viewer.py
  glue/viewers/profile/qt/tests/test_profile_tools.py
  glue/viewers/profile/state.py
  glue/viewers/profile/tests/test_state.py
  glue/viewers/scatter/layer_artist.py
  setup.py
Labels: enhancement, no-changelog-entry-needed, performance

#1643 Implement profile normalization
  glue/core/fitters.py
  glue/core/subset.py
  glue/main.py
  glue/viewers/image/qt/data_viewer.py
  glue/viewers/profile/layer_artist.py
  glue/viewers/profile/qt/data_viewer.py
  glue/viewers/profile/qt/layer_style_editor.py
  glue/viewers/profile/qt/layer_style_editor.ui
  glue/viewers/profile/qt/options_widget.ui
  glue/viewers/profile/qt/profile_tools.py
  glue/viewers/profile/qt/tests/test_data_viewer.py
  glue/viewers/profile/state.py
  glue/viewers/profile/tests/test_state.py
Labels: enhancement, needs-more-tests, no-changelog-entry-needed

#1554 Improve performance of slicing
  CHANGES.md
  glue/viewers/image/qt/data_viewer.py
  glue/viewers/image/qt/tests/test_data_viewer.py
  glue/viewers/matplotlib/state.py
Labels: performance

#1642 Only deactivate default mouse mode if new tool is checkable
  glue/viewers/common/qt/toolbar.py
Labels: affects-dev, no-changelog-entry-needed

#1484 Implement on-the-fly reprojection
  glue/viewers/image/layer_artist.py
  glue/viewers/image/python_export.py
  glue/viewers/image/qt/tests/test_data_viewer.py
  glue/viewers/image/state.py
  glue/viewers/image/tests/test_state.py
Labels: enhancement, merge-when-ci-passes, viewer-image

#1649 Fix ignoring of matplotlibrc file
  CHANGES.md
  glue/_mpl_backend.py
Labels: bug

#1650 Significantly improve performance of slicing with reprojected images
  glue/core/component.py
  glue/core/data.py
  glue/viewers/image/layer_artist.py
  glue/viewers/image/state.py
Labels: needs-more-tests, performance, viewer-image

#1651 Make sure all subset states work with advanced integer index views
  glue/core/subset.py
  glue/core/tests/test_subset.py
  glue/utils/array.py
Labels: affects-dev, bug

#1659 Added a new metadata/header viewer for datasets/subsets
  CHANGES.md
  doc/conf.py
  glue/app/qt/layer_tree_widget.py
  glue/app/qt/metadata.py
  glue/app/qt/metadata.ui
  glue/app/qt/versions.py
  glue/core/data_factories/fits.py
  glue/utils/qt/dialogs.py
Labels: enhancement

#1660 Factor out code to find minimal format for set of values
  CHANGES.md
  glue/utils/array.py
  glue/utils/tests/test_array.py
  glue/viewers/common/qt/data_slice_widget.py
  glue/viewers/common/qt/tests/test_data_slice_widget.py
Labels: code-organization, merge-when-ci-passes

#1665 Miscellaneous fixes
  CHANGES.md
  glue/app/qt/metadata.py
  glue/core/component_link.py
  glue/core/coordinates.py
  glue/core/tests/test_coordinate_links.py
  glue/icons/glue_crosshair.png
  glue/icons/glue_crosshair.svg
  glue/viewers/image/layer_artist.py
  glue/viewers/image/pixel_selection_mode.py
  glue/viewers/image/qt/slice_widget.py
Labels: bug, enhancement

#1666 Fix bug related to indexing order
  glue/core/coordinates.py
  glue/core/tests/test_coordinates.py
  glue/viewers/image/state.py
  glue/viewers/image/tests/test_state.py
  glue/viewers/profile/layer_artist.py
Labels: affects-dev, bug

#1634 Make it possible to group tools into drop-downs
  CHANGES.md
  doc/customizing_guide/toolbar.rst
  glue/plugins/dendro_viewer/qt/data_viewer.py
  glue/plugins/tools/__init__.py
  glue/viewers/common/qt/data_viewer.py
  glue/viewers/common/qt/data_viewer_with_state.py
  glue/viewers/common/qt/tool.py
  glue/viewers/common/qt/toolbar.py
  glue/viewers/custom/qt/custom_viewer.py
  glue/viewers/histogram/qt/data_viewer.py
  glue/viewers/image/qt/data_viewer.py
  glue/viewers/image/qt/standalone_image_viewer.py
  glue/viewers/matplotlib/qt/data_viewer.py
  glue/viewers/matplotlib/qt/tests/test_toolbar.py
  glue/viewers/matplotlib/qt/toolbar.py
  glue/viewers/profile/qt/data_viewer.py
  glue/viewers/profile/qt/profile_tools.py
  glue/viewers/scatter/qt/data_viewer.py
Labels: enhancement

#1668 Miscellaneous fixes
  CHANGES.md
  glue/core/state.py
  glue/core/tests/test_data.py
  glue/viewers/common/qt/data_viewer.py
  glue/viewers/image/layer_artist.py
  glue/viewers/image/qt/profile_viewer_tool.py
  glue/viewers/image/qt/tests/test_data_viewer.py
  glue/viewers/profile/qt/options_widget.py
  glue/viewers/profile/qt/tests/test_data_viewer.py
  glue/viewers/profile/state.py
  glue/viewers/profile/tests/test_state.py
Labels: affects-dev, bug

#1669 Added information messages to help with the profile viewer and large data
  CHANGES.md
  glue/_settings_helpers.py
  glue/app/qt/preferences.py
  glue/app/qt/preferences.ui
  glue/config.py
  glue/core/qt/dialogs.py
  glue/utils/matplotlib.py
  glue/viewers/common/qt/data_viewer.py
  glue/viewers/common/qt/data_viewer_with_state.py
  glue/viewers/histogram/qt/data_viewer.py
  glue/viewers/image/qt/profile_viewer_tool.py
  glue/viewers/profile/qt/data_viewer.py
  glue/viewers/profile/qt/tests/test_data_viewer.py
  glue/viewers/profile/state.py
Labels: enhancement

#1670 Make finding combo data more backward-compatible
  glue/external/echo/qt/connect.py
  glue/utils/qt/widget_properties.py
Labels: affects-dev

#1671 Fix profile tool activation
  glue/viewers/common/qt/toolbar.py
  glue/viewers/matplotlib/qt/toolbar.py
  glue/viewers/profile/qt/profile_tools.py
Labels: affects-dev, needs-more-tests

#1661 Make it possible to have a 'None' entry in ComponentIDComboHelper
  CHANGES.md
  glue/core/data_combo_helper.py
  glue/core/tests/test_data_combo_helper.py
Labels: cubeviz, enhancement

#1679 Added new perceptually uniform matplotlib colormaps
  CHANGES.md
  doc/getting_started/images/link_editor.png
  doc/getting_started/index.rst
  glue/config.py
  glue/plugins/export_d3po.py
  glue/plugins/tests/test_d3po.py
Labels: enhancement

#1681 Fix serialization of non-serializable types in Data.meta
  CHANGES.md
  glue/app/qt/application.py
  glue/core/data_factories/fits.py
  glue/core/data_factories/tests/data/comment.fits
  glue/core/data_factories/tests/test_fits.py
  glue/core/state.py
  glue/core/tests/test_data.py
  glue/plugins/tests/test_d3po.py
Labels: bug, glue.core
