Repository glue-viz/glue, pull requests merged in 2019-06, with the labels that each got.

#2016 Update docker images in CircleCI config
  .circleci/config.yml
  .travis.yml
  setup.py
Labels: no-changelog-entry-needed

#2018 Enable spell checking in CI
  .test-docs.sh
  .travis.yml
  doc/conf.py
  doc/customizing_guide/custom_viewer.rst
  doc/faq.rst
  doc/getting_started/index.rst
  doc/known_issues.rst
  doc/python_guide/data_viewer_options.rst
  doc/spelling_wordlist.txt
  glue/config.py
  glue/core/application_base.py
  glue/core/fitters.py
  glue/core/hub.py
  glue/core/link_helpers.py
  glue/core/roi.py
  glue/core/subset.py
  glue/utils/matplotlib.py
  glue/utils/qt/mime.py
  glue/utils/qt/threading.py
Labels: documention, no-changelog-entry-needed, testing

#2020 No longer offer to merge datasets by default
  .travis.yml
  CHANGES.md
  doc/gui_guide/merging.rst
  doc/whatsnew/whatsnew.rst
  glue/app/qt/application.py
  glue/app/qt/layer_tree_widget.py
  glue/core/application_base.py
  glue/core/data_collection.py
  glue/core/data_factories/hdf5.py
  glue/core/data_factories/tests/test_hdf5.py
  glue/core/tests/test_application_base.py
  glue/dialogs/data_wizard/qt/tests/test_data_wizard.py
  glue/dialogs/link_editor/qt/tests/test_link_editor.py
  glue/main.py
  glue/plugins/tools/python_export.py
  glue/utils/qt/app.py
  glue/viewers/histogram/python_export.py
  glue/viewers/image/composite_array.py
  glue/viewers/image/qt/tests/test_regression.py
  glue/viewers/matplotlib/qt/tests/test_data_viewer.py
  glue/viewers/scatter/layer_artist.py
  glue/viewers/scatter/python_export.py
  glue/viewers/scatter/qt/tests/test_python_export.py
Labels: bug, enhancement, glue.core

#2022 Add more information about WCS linkage
  glue/core/link_helpers.py
  glue/dialogs/autolinker/qt/autolinker.py
  glue/dialogs/autolinker/qt/autolinker.ui
  glue/dialogs/link_editor/qt/link_editor_dialog.ui
  glue/dialogs/link_editor/qt/link_editor_widget.ui
  glue/dialogs/link_editor/state.py
  glue/plugins/wcs_autolinking/wcs_autolinking.py
Labels: affects-dev, enhancement

#2023 Fix path to data bundle when exporting Python script
  CHANGES.md
  glue/viewers/common/viewer.py
Labels: bug

#2026 Fix dragging of existing ROIs
  glue/core/roi.py
Labels: affects-dev, bug

#1929 Use setup.cfg and setuptools_scm
  .circleci/config.yml
  LICENSE
  doc/conf.py
  glue/version.py
  setup.cfg
  setup.py
  tox.ini
Labels: code-organization

#2024 Fix component -> attribute terminology in UI
  doc/customizing_guide/customization.rst
  glue/app/qt/merge.ui
  glue/app/qt/save_data.ui
  glue/dialogs/component_arithmetic/qt/component_arithmetic.ui
  glue/dialogs/component_arithmetic/qt/equation_editor.py
  glue/dialogs/component_arithmetic/qt/equation_editor.ui
  glue/dialogs/component_arithmetic/qt/tests/test_equation_editor.py
  glue/dialogs/component_manager/qt/component_manager.ui
  glue/dialogs/subset_facet/qt/subset_facet.ui
Labels: gui, no-changelog-entry-needed

#2021 Implement a human-readable str/repr for State objects
  CHANGES.md
  glue/core/state_objects.py
  glue/core/tests/test_state_objects.py
  glue/external/echo/list.py
Labels: enhancement

#1870 add more useful error message for selection
  glue/external/echo/selection.py
Labels: enhancement

#2028 Updates to documentation ahead of 0.15 release
  CHANGES.md
  doc/customizing_guide/coordinates.rst
  doc/customizing_guide/customization.rst
  doc/developer_guide/app_building.rst
  doc/developer_guide/developer_guide.rst
  doc/developer_guide/testing.rst
  doc/index.rst
  doc/installation/conda.rst
  doc/installation/dependencies.rst
  doc/installation/developer.rst
  doc/installation/pip.rst
  doc/installation/qt.rst
  doc/spelling_wordlist.txt
  doc/whatsnew/images/v0.15/autolink.png
  doc/whatsnew/images/v0.15/autolink_details.png
  doc/whatsnew/images/v0.15/complex_links.png
  doc/whatsnew/whatsnew.rst
  glue/_deps.py
  glue/app/qt/application.py
  glue/core/data_factories/astropy_table.py
  glue/dialogs/autolinker/qt/autolinker.py
  glue/dialogs/autolinker/qt/autolinker.ui
  glue/external/pvextractor/pvextractor.py
  glue/tests/test_deps.py
  setup.cfg
  tox.ini
Labels: documention

#2030 Fixed compatibility with latest version of astropy
  glue/core/data_factories/astropy_table.py
Labels: io

#2031 Fixes following 0.15.0 release
  CHANGES.md
  conftest.py
  doc/whatsnew/whatsnew.rst
  glue/__init__.py
  glue/conftest.py
  glue/core/io/qt/subset_mask.py
  glue/core/io/subset_mask.py
  glue/plugins/wcs_autolinking/__init__.py
  glue/plugins/wcs_autolinking/wcs_autolinking.py
  glue/version.py
  setup.cfg
  tox.ini
Labels: bug

#2032 Fix bug in autoconnect_callbacks_to_qt
  CHANGES.md
  glue/dialogs/link_editor/qt/link_editor.py
  glue/external/echo/qt/autoconnect.py
Labels: bug

#2034 Fixes to preferences dialog
  CHANGES.md
  glue/app/qt/preferences.py
  glue/app/qt/preferences.ui
Labels: bug
