Repository glue-viz/glue, pull requests merged in 2020-04, with the labels that each got.

#2115 Performance improvements
  CHANGES.md
  glue/core/data.py
  glue/core/fixed_resolution_buffer.py
  glue/utils/array.py
  glue/utils/tests/test_array.py
  glue/viewers/profile/layer_artist.py
  glue/viewers/profile/state.py
  glue/viewers/profile/tests/test_state.py
  setup.cfg
Labels: work in progress

#2095 Fix issue where profile of subset was not correctly hidden if the subset was emptied
  CHANGES.md
  glue/viewers/profile/layer_artist.py
Labels: bug

#2096 Fix #2003: Have a way of seeing what session file was opened
  CHANGES.md
  glue/app/qt/application.py
Labels: enhancement, merge-when-ci-passes

#2090 Fix bug #1931: when creating a new subset, use ReplaceMode
  CHANGES.md
  glue/core/command.py
Labels: enhancement

#2082 Profile Viewer Script Export
  glue/plugins/tools/__init__.py
  glue/viewers/profile/layer_artist.py
  glue/viewers/profile/python_export.py
  glue/viewers/profile/qt/tests/test_python_export.py
Labels: enhancement, viewer-profile

#2117 Fixed missing .units on CoordinateComponent
  CHANGES.md
  glue/core/component.py
  glue/core/data_factories/tests/test_fits.py
Labels: bug
