Repository glue-viz/glue, pull requests merged in 2022-10, with the labels that each got.

#2327 Fix bugs in BaseCartesianData.get_data for pixel and world component IDs
  glue/core/data.py
  glue/core/tests/test_data.py
Labels: bug, abstract-data

#2324 Fix issue where matplotlib viewers using ``y`` log axes were not initialized correctly.
  glue/viewers/matplotlib/viewer.py
Labels: bug

#2322 Export color settings in matplotlib viewers
  CHANGES.md
  glue/viewers/image/viewer.py
  glue/viewers/matplotlib/mpl_axes.py
  glue/viewers/matplotlib/qt/tests/test_python_export.py
  glue/viewers/matplotlib/viewer.py
Labels: enhancement

#2331 Setup automated changelog generation for release process
  .github/release.yml
  .github/workflows/update-changelog.yaml
  CHANGES.md
  RELEASE.rst
  doc/developer_guide/developer_guide.rst
  doc/developer_guide/release.rst
Labels: documention, no-changelog-entry-needed

#2318 Add support for PyQt6 and PySide6 (<6.4) to Qt backends
  .github/workflows/ci_workflows.yml
  glue/app/qt/layer_tree_widget.py
  glue/app/qt/plugin_manager.py
  glue/app/qt/preferences.ui
  glue/app/qt/splash_screen.py
  glue/app/qt/tests/test_layer_tree_widget.py
  glue/conftest.py
  glue/core/qt/layer_artist_model.py
  glue/dialogs/autolinker/qt/autolinker.py
  glue/dialogs/component_arithmetic/qt/component_arithmetic.ui
  glue/dialogs/component_arithmetic/qt/equation_editor.ui
  glue/dialogs/component_manager/qt/component_manager.ui
  glue/dialogs/link_editor/qt/link_editor_widget.ui
  glue/dialogs/subset_facet/qt/subset_facet.ui
  glue/plugins/dendro_viewer/qt/options_widget.ui
  glue/utils/qt/app.py
  glue/utils/qt/mime.py
  glue/utils/qt/tests/test_widget_properties.py
  glue/viewers/histogram/qt/options_widget.ui
  glue/viewers/image/qt/layer_style_editor.ui
  glue/viewers/image/qt/options_widget.ui
  glue/viewers/profile/qt/layer_style_editor.ui
  glue/viewers/profile/qt/options_widget.ui
  glue/viewers/scatter/qt/layer_style_editor.ui
  glue/viewers/scatter/qt/options_widget.ui
Labels: enhancement

#2339 Update changelog order in `release.yml`, deprecate Azure badge.
  .github/release.yml
  README.rst
Labels: documentation, no-changelog-entry-needed

#2342 Fix typo in dialog message.
  glue/core/qt/dialogs.py
Labels: bug, no-changelog-entry-needed

#2338 Add PyQt6 and PySide6 status to `glue-deps` information
  glue/_deps.py
Labels: documentation

#2335 Fix export to Python script to correctly use `Coordinates` or `WCS` in `reference_data`
  glue/viewers/image/qt/tests/test_python_export.py
  glue/viewers/image/viewer.py
Labels: bug, glue.viewers, viewer-image
