Repository glue-viz/glue, pull requests merged in 2023-10, with the labels that each got.

#2425 Fix bug that caused incompatible subsets to be rendered in some contexts rather than be hidden
  glue/viewers/image/layer_artist.py
Labels: bug

#2446 Support dynamic components
  glue/core/data.py
  glue/core/layer_artist.py
  glue/core/message.py
  glue/core/tests/test_components_changed.py
  glue/viewers/common/tests/test_viewer.py
  glue/viewers/common/viewer.py
Labels: enhancement

#2442 Add regiondata
  doc/conf.py
  glue/core/component.py
  glue/core/data.py
  glue/core/data_region.py
  glue/core/regions.py
  glue/core/state.py
  glue/core/tests/test_component.py
  glue/core/tests/test_data_region.py
  setup.cfg
Labels: enhancement

#2450 Fix compatibility with latest developer version of astropy
  .readthedocs.yml
  glue/plugins/coordinate_helpers/link_helpers.py
Labels: bug

#2451 Fix bug when changing the number of bins on a histogram with modified/deleted data
  glue/core/application_base.py
  glue/core/state_objects.py
  glue/viewers/histogram/tests/test_state.py
Labels: bug

#2452 Fix docs failure related to theme warning
  doc/conf.py
Labels: documentation
