Repository glue-viz/glue, pull requests merged in 2023-03, with the labels that each got.

#2369 DOC: Fix equivalent_units in examples
  doc/customizing_guide/units.rst
Labels: documentation

#2377 Fixed a bug in the plugin iteration on Python 3.8 and 3.9
  glue/_plugin_helpers.py
  setup.cfg
Labels: bug

#2367 TST: Fix typo in test case
  glue/core/tests/test_units.py
Labels: no-changelog-entry-needed

#2360 Add pretransform for full-sphere selection
  glue/core/roi_pretransforms.py
  glue/viewers/scatter/qt/tests/test_data_viewer.py
  glue/viewers/scatter/viewer.py
Labels: bug

#2372 Only recreate table model when Data layer changes
  glue/viewers/table/qt/data_viewer.py
  glue/viewers/table/qt/tests/test_data_viewer.py
Labels: bug, viewer-table
