Repository glue-viz/glue, pull requests merged in 2023-01, with the labels that each got.

#2349 More fixes for compatibility with Qt6
  glue/dialogs/link_editor/qt/data_graph.py
  glue/main.py
Labels: bug

#2345 Fix world coordinates for 1D WCS
  glue/core/component.py
  glue/core/component_link.py
  glue/core/coordinate_helpers.py
  glue/core/coordinates.py
  glue/core/data.py
  glue/core/fixed_resolution_buffer.py
  glue/core/subset.py
  glue/core/tests/test_component.py
  glue/core/tests/test_coordinates.py
  glue/core/tests/test_data.py
  glue/core/tests/test_links.py
  glue/utils/array.py
  glue/utils/geometry.py
  glue/utils/tests/test_array.py
  glue/viewers/image/layer_artist.py
  glue/viewers/scatter/layer_artist.py
Labels: bug, glue.core

#2352 Pin numpy-dev to avoid `GlueSerializer` failure on `numpy._ArrayFunctionDispatcher`
  tox.ini
Labels: bug

#2350 Allow specifying visual attributes and colormap when faceting subsets
  glue/core/tests/test_util.py
  glue/core/util.py
  glue/dialogs/subset_facet/qt/subset_facet.py
  glue/dialogs/subset_facet/qt/tests/test_subset_facet.py
Labels: enhancement, matplotlib
