Repository glue-viz/glue, pull requests merged in 2023-08, with the labels that each got.

#2429 Skip `test_save_aggregate_slice` for Numpy 1.25.x and unpin numpy-dev
  .github/workflows/ci_workflows.yml
  glue/viewers/image/qt/tests/test_data_viewer.py
  tox.ini
Labels: testing

#2422 Set better starting xlim and ylim for custom viewers
  glue/viewers/custom/qt/custom_viewer.py
Labels: bug, documentation

#2427 Render nans as 'bad' in mpl cmaps when mode='colormap'
  glue/viewers/image/composite_array.py
  glue/viewers/image/tests/test_composite_array.py
Labels: bug, matplotlib
