Repository glue-viz/glue, pull requests merged in 2023-02, with the labels that each got.

#2356 Represent `None` `component.units` as empty strings
  glue/core/component.py
Labels: bug, glue.core

#2355 Move PySide builds to allowed failures
  .github/workflows/ci_workflows.yml
  doc/conf.py
  doc/developer_guide/api.rst
Labels: no-changelog-entry-needed

#2358 Ensure unit choices are updated when x_att is changed in profile viewer
  glue/viewers/profile/state.py
Labels: bug, merge-when-ci-passes, viewer-profile

#2348 Relax longitude range in fullsphere projections
  glue/viewers/scatter/layer_artist.py
  glue/viewers/scatter/python_export.py
  glue/viewers/scatter/qt/options_widget.py
  glue/viewers/scatter/qt/tests/test_data_viewer.py
  glue/viewers/scatter/qt/tests/test_python_export.py
  glue/viewers/scatter/viewer.py
Labels: enhancement

#2366 Update polar log transform test values to correct matplotlib 3.7 representation
  glue/core/tests/test_roi_transforms.py
  glue/tests/helpers.py
Labels: bug, matplotlib
