Repository glue-viz/glue, pull requests merged in 2023-05, with the labels that each got.

#2391 Make ROI.move_to() behave consistently and expose it at subset_state level
  glue/core/roi.py
  glue/core/subset.py
  glue/core/tests/test_roi.py
  glue/core/tests/test_subset.py
  glue/utils/geometry.py
Labels: bug, ROIs

#2400 Fix bugs with unit conversion when changing x/y attributes
  glue/viewers/profile/qt/tests/test_data_viewer.py
  glue/viewers/profile/state.py
Labels: bug

#2392 Add filter/search to table viewer
  glue/viewers/table/compat.py
  glue/viewers/table/qt/data_viewer.py
  glue/viewers/table/qt/data_viewer.ui
  glue/viewers/table/qt/tests/test_data_viewer.py
  glue/viewers/table/state.py
Labels: viewer-table

#2387 Add functionality for moving viewers between tabs
  glue/app/qt/application.py
  glue/app/qt/tests/test_application.py
  glue/icons/windows.png
  glue/viewers/common/qt/__init__.py
  glue/viewers/common/qt/data_viewer.py
  glue/viewers/common/qt/tools.py
Labels: gui, qt
