Repository glue-viz/glue, pull requests merged in 2023-04, with the labels that each got.

#2380 Save legend state
  glue/viewers/matplotlib/state.py
  glue/viewers/matplotlib/tests/test_state.py
Labels: bug, enhancement

#2344 Fix bugs related to generic BaseCartesianData subclasses
  glue/core/data_collection.py
  glue/viewers/common/viewer.py
  glue/viewers/image/state.py
  glue/viewers/image/viewer.py
Labels: bug

#2389 Fix bad connections in tutorial examples
  doc/customizing_guide/mpl_viewer/config.py
  doc/customizing_guide/qt_viewer.rst
  doc/customizing_guide/state_viewer/config.py
Labels: documentation
