Repository glue-viz/glue, pull requests merged in 2024-09, with the labels that each got.

#2513 Correct y limits in ProfileViewerState when min same as max
  glue/viewers/profile/state.py
  glue/viewers/profile/tests/test_state.py
Labels: bug, cubeviz, viewer-profile

#2519 Fix an issue that caused the astropy table reader on Windows to behave differently to other platforms
  glue/core/data_factories/astropy_table.py
Labels: bug

#2518 Add CI for Python 3.13 and update dev envs
  .github/workflows/ci_workflows.yml
  tox.ini
Labels: no-changelog-entry-needed, testing

#2516 Remove documentation for py38 and 39
  setup.cfg
Labels: no-changelog-entry-needed
