Repository glue-viz/glue, pull requests merged in 2024-04, with the labels that each got.

#2475 Allow serializing and deserializing named astropy units
  glue/core/state.py
  glue/core/tests/test_state.py
Labels: enhancement, io

#2484 Fix bugs with attribute display units
  glue/config_gen.py
  glue/core/state_objects.py
  glue/main.py
  glue/viewers/image/state.py
  glue/viewers/matplotlib/tests/test_state.py
Labels: bug

#2471 Compatibility and tests against Numpy 2.0.0rc1
  .github/workflows/ci_workflows.yml
  glue/utils/array.py
  setup.cfg
  tox.ini
Labels: bug, no-changelog-entry-needed, testing

#2476 Allow setting slices or `subset_state` for determining min/max levels in `StateAttributeLimitsHelper`
  glue/core/state_objects.py
  glue/core/tests/test_state_objects.py
  glue/viewers/image/state.py
  glue/viewers/image/tests/test_state.py
Labels: enhancement, glue.viewers, viewer-image, cubeviz
