Repository glue-viz/glue, pull requests merged in 2025-03, with the labels that each got.

#2531 Add pre-commit and Ruff setup with flake8 and other codestyle checks
  .pre-commit-config.yaml
  .ruff.toml
  pyproject.toml
  tox.ini
Labels: testing, Infrastructure

#2532 Fix regexp for command parser
  glue/core/parse.py
Labels: bug, linking

#2533 Fix int dtype test
  glue/core/data_factories/tests/test_data_factories.py
Labels: bug, io
